region:
  - Субъект РФ
  - Регион
  - субъект рф
  - регион
  - Область
  - область
  - республика
  - край
  - автономный округ
  - Субъект
  - субъект

fullname:
  - ФИО
  - фио
  - Ф.И.О.
  - Ф И О
  - Полное имя
  - Имя
  - Фамилия Имя Отчество
  - Фамилия, имя, отчество

participants_type:
  - Тип слушателя
  - тип слушателя
  - Категория слушателя
  - категория слушателя
  - Тип участника
  - тип участника

participants_spec:
  - специализация слушателя
  - Специализация слушателя
  - Специальность
  - специальность
  - Направление подготовки
  - направление подготовки

affiliation_org:
  - место работы/учебы
  - Место работы/учебы
  - Организация
  - организация
  - Место работы
  - место работы
  - Учебное заведение
  - учебное заведение
  - Работодатель
  - работодатель

affiliation_org_type:
  - Тип места работы/учебы
  - тип места работы/учебы
  - Тип организации
  - тип организации
  - Форма организации
  - форма организации

edu_org_name:
  - ОУ ПК
  - Наиемнование ОУ
  - Наименование ОУ
  - ОУ
  - оу
  - Название учебного заведения
  - Название ОУ
  - название оу
  - Учебное заведение
  - учебное заведение

training_program_provider:
  - Разработчик программы ПК
  - разработчик программы пк
  - Организация-разработчик
  - организация-разработчик
  - Провайдер программы
  - провайдер программы

training_program_name:
  - Намиенование программы обучения
  - Наименование программы обучения
  - Название программы
  - название программы
  - Программа ПК
  - программа пк
  - Программа повышения квалификации
  - программа повышения квалификации

num_hours:
  - Количество часов
  - количество часов
  - Часы
  - часы
  - Объём часов
  - объём часов
  - Длительность (часы)
  - длительность (часы)

study_mode:
  - Форма обучения
  - форма обучения
  - Тип обучения
  - тип обучения
  - Очно/заочно
  - очно/заочно
  - Формат обучения
  - формат обучения

start_date:
  - Дата начала
  - дата начала
  - Начало
  - начало
  - Дата старта
  - дата старта
  - Start date
  - start date

end_date:
  - Дата окончания
  - дата окончания
  - Окончание
  - окончание
  - Дата завершения
  - дата завершения
  - End date
  - end date

settlement:
  - Населенный пункт
  - Населённы пункт
  - населенный пункт
  - населённый пункт
  - Город
  - город
  - Посёлок
  - посёлок
  - Нас. пункт
  - нас. пункт
  - Место проведения
  - место проведения

municipality:
  - Муниципальный р-н
  - муниципальный р-н
  - Район
  - район
  - Муниципальный район
  - муниципальный район
  - Муниципалитет
  - муниципалитет
  - р-н
  - р.н.
  - р. н.
  - муниципальный р.
  - муниципальный р
  - Административный район
  - административный район

im_name:
  - Наименование ИМ
  - наименование им
  - Название ИМ
  - название им
  - ИМ
  - им
  - Информационный материал
  - информационный материал

im_type:
  - Тип ИМ
  - тип им
  - Вид ИМ
  - вид им
  - Категория ИМ
  - категория им

im_topic:
  - Тематика ИМ
  - тематика им
  - Тема ИМ
  - тема им
  - Содержание ИМ
  - содержание им

im_format:
  - Формат ИМ
  - формат им
  - Тип материала
  - тип материала
  - Формат материала
  - формат материала

pp_name:
  - Наименование ТР
  - наименование тр
  - Название ТР
  - название тр
  - ТР
  - тр
  - Точка роста
  - точка роста

pp_type:
  - Тип ТР
  - тип тр
  - Категория ТР
  - категория тр

im_url:
  - URL-размещённых материалов
  - url-размещённых материалов
  - Ссылка на материалы
  - ссылка на материалы
  - URL материалов
  - url материалов
  - Сайт
  - сайт

age_group:
  - Возрастная группа
  - возрастная группа
  - Возраст
  - возраст
  - Возраст участников
  - возраст участников

social_group:
  - Социальная группа
  - социальная группа
  - Целевая группа
  - целевая группа
  - Категория граждан
  - категория граждан

organizer_name:
  - Организация
  - организация
  - Организатор
  - организатор
  - Устроитель
  - устроитель
  - Ответственная организация
  - ответственная организация

department:
  - Подразделение
  - подразделение
  - Департамент
  - департамент
  - Отдел
  - отдел
  - Управление
  - управление

personInCharge:
  - Ответственный
  - ответственный
  - Контактное лицо
  - контактное лицо
  - Руководитель
  - руководитель
  - ФИО ответственного
  - фио ответственного

partner_name:
  - Наименование партнера
  - наименование партнера
  - Партнер
  - партнер
  - Название партнёра
  - название партнёра
  - Организация-партнёр
  - организация-партнёр

partner_type:
  - Тип партнёра
  - тип партнёра
  - Категория партнёра
  - категория партнёра
  - Роль партнёра
  - роль партнёра

palcement_date:
  - Дата размещения
  - дата размещения
  - Дата публикации
  - дата публикации
  - Дата загрузки
  - дата загрузки

views_cnt:
  - Количество просмотров
  - количество просмотров
  - Просмотры
  - просмотры
  - Views
  - views

im_cnt:
  - Количество размещённых материалов
  - количество размещённых материалов
  - Число материалов
  - число материалов
  - Материалы
  - материалы

edu_org_type:
  - Тип ОУ
  - тип оу
  - Вид образовательной организации
  - вид образовательной организации
  - Форма ОУ
  - форма оу

hasFinLit:
  - ПФГ Внедерена
  - пфг внедерена
  - ПФГ внедрена
  - пфг внедрена
  - Есть ПФГ
  - есть пфг
  - Финансовая грамотность
  - финансовая грамотность
  - Программа ПФГ
  - программа пфг

edu_program_name:
  - Образовательная программа
  - образовательная программа
  - Программа обучения
  - программа обучения
  - Учебная программа
  - учебная программа

students_cnt:
  - количество учеников
  - Количество учеников
  - Число учеников
  - число учеников
  - Учащиеся
  - учащиеся
  - Студенты
  - студенты

studentsWithFinLit_cnt:
  - количество учеников по ПФГ
  - Количество учеников по ПФГ
  - Учащиеся по ПФГ
  - учащиеся по пфг
  - Студенты с ПФГ
  - студенты с пфг

teachers_cnt:
  - количество преподавателей
  - Количество преподавателей
  - Число педагогов
  - число педагогов
  - Педагоги
  - педагоги
  - Учителя
  - учителя

teachersFinLitTraining_cnt:
  - количество преподавателей по ПФГ
  - Количество преподавателей по ПФГ
  - Педагоги по ПФГ
  - педагоги по пфг
  - Обученные учителя
  - обученные учителя

event:
  - Мероприятие
  - мероприятие
  - Название мероприятия
  - название мероприятия
  - Событие
  - событие

event_type:
  - Тип мероприятия
  - тип мероприятия
  - Вид мероприятия
  - вид мероприятия
  - Категория мероприятия
  - категория мероприятия

event_format:
  - Формат мероприятия
  - формат мероприятия
  - Очно/онлайн
  - очно/онлайн
  - Гибрид
  - гибрид

event_topic:
  - Тема мероприятия
  - тема мероприятия
  - Тематика
  - тематика
  - Направление
  - направление

volunteers:
  - Волонтеры
  - волонтеры
  - Волонтёры
  - волонтёры
  - Добровольцы
  - добровольцы

volunteers_type:
  - Тип волонтёров
  - тип волонтёров
  - Категория волонтёров
  - категория волонтёров
  - Роль волонтёров
  - роль волонтёров

date:
  - Дата проведения
  - дата проведения
  - Дата
  - дата
  - Дата мероприятия
  - дата мероприятия
  - Event date
  - event date

participants_cnt:
  - Количество участников
  - количество участников
  - Участники
  - участники
  - Число участников
  - число участников