region:
  type: string
  db_field: region
  db_table: dim_location
  matches:
    - Субъект РФ
    - Регион
    - субъект рф
    - регион
    - Область
    - область
    - республика
    - край
    - автономный округ
    - Субъект
    - субъект

fullname:
  type: string
  db_field: name
  db_table: dim_staff
  matches:
    - ФИО
    - фио
    - Ф.И.О.
    - Ф И О
    - Полное имя
    - Имя
    - Фамилия Имя Отчество
    - Фамилия, имя, отчество

# participants = Слушатель
participants_type:
  type: string
  db_field: type
  db_table: dim_staff
  matches:
    - Тип слушателя
    - тип слушателя
    - Категория слушателя
    - категория слушателя
    - Тип участника
    - тип участника

participants_spec:
  type: string
  db_field: spec
  db_table: dim_staff
  matches:
    - специализация слушателя
    - Специализация слушателя
    - Специальность
    - специальность
    - Направление подготовки
    - направление подготовки

#Организация в которой учится/работает слушатель
affiliation_org:
  type: string
  db_field: name
  db_table: dim_organization
  matches:
    - место работы/учебы
    - Место работы/учебы
    - Организация
    - организация
    - Место работы
    - место работы
    - Учебное заведение
    - учебное заведение
    - Работодатель
    - работодатель

affiliation_org_type:
  type: string
  db_field: type
  db_table: dim_organization
  matches:
    - Тип места работы/учебы
    - тип места работы/учебы
    - Тип организации
    - тип организации
    - Форма организации
    - форма организации

edu_org_name:
  type: string
  db_field: name
  db_table: dim_organization
  matches:
    - ОУ ПК
    - Наиемнование ОУ
    - Наименование ОУ
    - ОУ
    - оу
    - Название учебного заведения
    - Название ОУ
    - название оу
    - Учебное заведение
    - учебное заведение

training_program_provider:
  type: string
  db_field: name
  db_table: dim_organization
  matches:
    - Разработчик программы ПК
    - разработчик программы пк
    - Организация-разработчик
    - организация-разработчик
    - Провайдер программы
    - провайдер программы

training_program_name:
  type: string
  db_field: name
  db_table: dim_training_program
  matches:
    - Намиенование программы обучения
    - Наименование программы обучения
    - Название программы
    - название программы
    - Программа ПК
    - программа пк
    - Программа повышения квалификации
    - программа повышения квалификации

num_hours:
  type: float
  db_field: duration_hours
  db_table: dim_training_program
  matches:
    - Количество часов
    - количество часов
    - Часы
    - часы
    - Объём часов
    - объём часов
    - Длительность (часы)
    - длительность (часы)

study_mode:
  type: string
  db_field: study_mode
  db_table: fact_trainings
  matches:
    - Форма обучения
    - форма обучения
    - Тип обучения
    - тип обучения
    - Очно/заочно
    - очно/заочно
    - Формат обучения
    - формат обучения

start_date:
  type: datetime64[ns]
  db_field: date
  db_table: dim_date
  matches:
    - Дата начала
    - дата начала
    - Начало
    - начало
    - Дата старта
    - дата старта
    - Start date
    - start date

end_date:
  type: datetime64[ns]
  db_field: date
  db_table: dim_date
  matches:
    - Дата окончания
    - дата окончания
    - Окончание
    - окончание
    - Дата завершения
    - дата завершения
    - End date
    - end date

settlement:
  type: string
  db_field: settlement
  db_table: dim_location
  matches:
    - Населенный пункт
    - Населённы пункт
    - населенный пункт
    - населённый пункт
    - Город
    - город
    - Посёлок
    - посёлок
    - Нас. пункт
    - нас. пункт
    - Место проведения
    - место проведения

municipality:
  type: string 
  db_field: municipality
  db_table: dim_location
  matches:
    - Муниципальный р-н
    - муниципальный р-н
    - Район
    - район
    - Муниципальный район
    - муниципальный район
    - Муниципалитет
    - муниципалитет
    - р-н
    - р.н.
    - р. н.
    - муниципальный р.
    - муниципальный р
    - Административный район
    - административный район

im_name:
  type: string
  db_field: name
  db_table: dim_info_material
  matches:
    - Наименование ИМ
    - наименование им
    - Название ИМ
    - название им
    - ИМ
    - им
    - Информационный материал
    - информационный материал

im_type:
  type: string
  db_field: type
  db_table: dim_info_material
  matches:
    - Тип ИМ
    - тип им
    - Вид ИМ
    - вид им
    - Категория ИМ
    - категория им

im_topic:
  type: string
  db_field: topic
  db_table: dim_info_material
  matches:
    - Тематика ИМ
    - тематика им
    - Тема ИМ
    - тема им
    - Содержание ИМ
    - содержание им

im_format:
  type: string
  db_field: format
  db_table: dim_info_material
  matches:
    - Формат ИМ
    - формат им
    - Тип материала
    - тип материала
    - Формат материала
    - формат материала

pp_name:
  type: string
  db_field: name
  db_table: dim_PlacementPoint
  matches:
    - Наименование ТР
    - наименование тр
    - Название ТР
    - название тр
    - ТР
    - тр
    - Точка Размешения
    - точка размешения
    - Наименование точки размешения

pp_type:
  type: string
  db_field: type
  db_table: dim_PlacementPoint
  matches:
    - Тип ТР
    - тип тр
    - Категория ТР
    - категория тр

im_url:
  type: string
  db_field: url
  db_table: fact_im_placements
  matches:
    - URL-размещённых материалов
    - url-размещённых материалов
    - Ссылка на материалы
    - ссылка на материалы
    - URL материалов
    - url материалов
    - Сайт
    - сайт

age_group:
  type: string
  db_field: age_group
  db_table: dim_audience
  matches:
    - Возрастная группа
    - возрастная группа
    - Возраст
    - возраст
    - Возраст участников
    - возраст участников

social_group:
  type: string
  db_field: soc_group
  db_table: dim_audience
  matches:
    - Социальная группа
    - социальная группа
    - Целевая группа
    - целевая группа
    - Категория граждан
    - категория граждан

organizer_name:
  type: string
  db_field: organization
  db_table: dim_staff
  matches:
    - Организация
    - организация
    - Организатор
    - организатор
    - Устроитель
    - устроитель
    - Ответственная организация
    - ответственная организация

department:
  type: string
  db_field: department
  db_table: dim_staff
  matches:
    - Подразделение
    - подразделение
    - Департамент
    - департамент
    - Отдел
    - отдел
    - Управление
    - управление

personInCharge:
  type: string
  db_field: name
  db_table: dim_staff
  matches:
    - Ответственный
    - ответственный
    - Контактное лицо
    - контактное лицо
    - Руководитель
    - руководитель
    - ФИО ответственного
    - фио ответственного

partner_name:
  type: string
  db_field: name
  db_table: dim_partner
  matches:
    - Наименование партнера
    - наименование партнера
    - Партнер
    - партнер
    - Название партнёра
    - название партнёра
    - Организация-партнёр
    - организация-партнёр

partner_type:
  type: string
  db_field: type
  db_table: dim_partner
  matches:
    - Тип партнёра
    - тип партнёра
    - Категория партнёра
    - категория партнёра
    - Роль партнёра
    - роль партнёра

palcement_date:
  type: datetime64[ns]
  db_field: date
  db_table: dim_date
  matches:
    - Дата размещения
    - дата размещения
    - Дата публикации
    - дата публикации
    - Дата загрузки
    - дата загрузки

views_cnt:
  type: int
  db_field: views_cnt
  db_table: fact_im_placements
  matches:
    - Количество просмотров
    - количество просмотров
    - Просмотры
    - просмотры
    - Views
    - views

im_cnt:
  type: int
  db_field: posted_materials_cnt
  db_table: fact_im_placements
  matches:
    - Количество размещённых материалов
    - количество размещённых материалов
    - Число материалов
    - число материалов
    - Материалы
    - материалы

edu_org_type:
  type: string
  db_field: type
  db_table: dim_organization
  matches:
    - Тип ОУ
    - тип оу
    - Вид образовательной организации
    - вид образовательной организации
    - Форма ОУ
    - форма оу

hasFinLit:
  type: bool
  db_field: hasFinLit
  db_table: fact_edu_integrations
  matches:
    - ПФГ Внедерена
    - пфг внедерена
    - ПФГ внедрена
    - пфг внедрена
    - Есть ПФГ
    - есть пфг
    - Финансовая грамотность
    - финансовая грамотность
    - Программа ПФГ
    - программа пфг

edu_program_name:
  type: string
  db_field: name
  db_table: dim_edu_program
  matches:
    - Образовательная программа
    - образовательная программа
    - Программа обучения
    - программа обучения
    - Учебная программа
    - учебная программа

students_cnt:
  type: int
  db_field: students_cnt
  db_table: fact_edu_integrations
  matches:
    - количество учеников
    - Количество учеников
    - Число учеников
    - число учеников
    - Учащиеся
    - учащиеся
    - Студенты
    - студенты

students_with_finlit_cnt:
  type: int
  db_field: students_with_finlit_cnt
  db_table: fact_edu_integrations
  matches:
    - количество учеников по ПФГ
    - Количество учеников по ПФГ
    - Учащиеся по ПФГ
    - учащиеся по пфг
    - Студенты с ПФГ
    - студенты с пфг

teachers_cnt:
  type: int
  db_field: teachers_cnt
  db_table: fact_edu_integrations
  matches:
    - количество преподавателей
    - Количество преподавателей
    - Число педагогов
    - число педагогов
    - Педагоги
    - педагоги
    - Учителя
    - учителя

teachers_finlit_train_cnt:
  type: int
  db_field: teachers_fin_lit_trained_cnt
  db_table: fact_edu_integrations
  matches:
    - количество преподавателей по ПФГ
    - Количество преподавателей по ПФГ
    - Педагоги по ПФГ
    - педагоги по пфг
    - Обученные учителя
    - обученные учителя

event:
  type: string
  db_field: event_name
  db_table: fact_events
  matches:
    - Мероприятие
    - мероприятие
    - Название мероприятия
    - название мероприятия
    - Событие
    - событие

event_type:
  type: string
  db_field: type
  db_table: dim_event
  matches:
    - Тип мероприятия
    - тип мероприятия
    - Вид мероприятия
    - вид мероприятия
    - Категория мероприятия
    - категория мероприятия

event_format:
  type: string
  db_field: format
  db_table: dim_event
  matches:
    - Формат мероприятия
    - формат мероприятия
    - Очно/онлайн
    - очно/онлайн
    - Гибрид
    - гибрид

event_topic:
  type: string
  db_field: topic
  db_table: dim_event
  matches:
    - Тема мероприятия
    - тема мероприятия
    - Тематика
    - тематика
    - Направление
    - направление

volunteers:
  type: string
  db_field: name
  db_table: dim_staff
  matches:
    - Волонтеры
    - волонтеры
    - Волонтёры
    - волонтёры
    - Добровольцы
    - добровольцы

volunteers_type:
  type: string
  db_field: type
  db_table: dim_staff
  matches:
    - Тип волонтёров
    - тип волонтёров
    - Категория волонтёров
    - категория волонтёров
    - Роль волонтёров
    - роль волонтёров

date:
  type: datetime64[ns]
  db_field: date
  db_table: dim_date
  matches:
    - Дата проведения
    - дата проведения
    - Дата
    - дата
    - Дата мероприятия
    - дата мероприятия
    - Event date
    - event date

participants_cnt:
  type: int
  db_field: participants_cnt
  db_table: fact_events
  matches:
    - Количество участников
    - количество участников
    - Участники
    - участники
    - Число участников
    - число участников