dimensions:
  dim_Location:
    id: location_id
    natural_key_columns:
      - region
      - municipality
      - settlement
  dim_Event:
    id: event_id
    natural_key_columns:
      - name
      - type
      - format
      - topic
  dim_Partner:
    id: partner_id
    natural_key_columns: [name, type]
  dim_Audience:
    id: audience_id
    natural_key_columns: [age_group, soc_group]
  dim_PlacementPoint:
    id: placement_point_id
    natural_key_columns: [name, type]
  dim_InfoMaterials:
    id: info_materials_id
    natural_key_columns: [name, type, topic, format]
  dim_TrainingProgram:
    id: training_program_id
    natural_key_columns: [name, provider, duration_hours]
  dim_Date:
    id: date_id
    natural_key_columns: [date]
  dim_Organization:
    id: organization_id
    natural_key_columns: [name, type]
  dim_Staff:
    id: staff_id
    natural_key_columns: [name, department, organization_id]
facts:
  fact_Events:
    id: fact_event_id
    columns:
      - is_edu_materials_used
      - auditorium
      - event_name
      - location_id
      - partner_id
      - event_id
      - audience_id
      - organizer_id
      - date_id
      - participants_cnt
      - volunteers_cnt
  volunteersInEvent: # Вспомогательная таблица для свизи волонтеров и мероприятий в которых они учавствовали
    id: ''
    columns:
      - event_id
      - staff_id
      - comment
  fact_Training:
    id: ''
    columns:
      - study_mode # дегенеративное измерение
      - location_id # Географическое Место проведения ПК
      - training_provider_id # Организация на базе которой проводится ПК, dim_Organization.id
      - training_program_id # //Программа повышения квалификации(разраб программы, длительность название)
      - staff_id # Слушатель прошедший обучение (тип специализация)
      - affiliation_org_id # Место работы/учебы слушателя
      - start_date_id
      - end_date_id
  fact_EduIntegration:
    id: ''
    columns:
      - hasFinLit
      - location_id # Геогрфическоя привязка 
      - organization_id # Образовательное учреждение
      - edu_program_id  # Образовательная программа(начального, общего, среднего и т.п.)
      - teachers_cnt                
      - teachersFinLitTrained_cnt   
      - teachersFinLitTraining_cnt  
      - students_cnt                
      - studentsWithFinLit_cnt
  fact_ImPlacementPoint:
    id: ''
    columns:
      - location_id
      - placement_point_id
      - info_mat_id
      - partner_id
      - audience_id
      - organizer_id
      - date_id
      - views_cnt # Количество реальных или прогрнозируемых просмотров
      - posted_materials_cnt 
      